
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = "1.8.12"

[[constraint]]
  name = "github.com/ipfs/go-ipld-cbor"
  branch = "feat/refmt-pool"

[[constraint]]
  name = "github.com/multiformats/go-multihash"
  version = "1.0.8"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"
